#! /usr/bin/env ruby
require 'thor'
require File.join(File.dirname(__FILE__), 'lib')


class App < Thor
  map '-f' => :fetch_corpus

  desc "-f/fetch_corpus", "fetch one million sentences corpus into corpus.txt"
  def fetch_corpus
    `wget http://d3t3fd87rd28b5.cloudfront.net/one_meelyun_sentences.bz2`
    `bzip2 -d one_meelyun_sentences.bz2`
    `mv one_meelyun_sentences corpus.txt`
  end
end

App.start

